`ifndef __YUTORINA_GLOBAL_CONFIG_H__
`define __YUTORINA_GLOBAL_CONFIG_H__

`define YUTORINA_POSITIVE_RESET
`define YUTORINA_NEGATIVE_RESET

`define YUTORINA_POSITIVE_MEMORY
`define YUTORINA_NEGATIVE_MEMORY

`define YUTORINA_IMPLEMENT_TIMER
`define YUTORINA_IMPLEMENT_UART
`define YUTORINA_IMPLEMENT_GPIO

`ifdef YUTORINA_POSITIVE_RESET
`define YUTORINA_RESET_EDGE posedge
`else
`define YUTORINA_RESET_EDGE negedge
`endif

`ifdef YUTORINA_POSITIVE_RESET
`define YUTORINA_RESET_ENABLE 1'b1
`else
`define YUTORINA_RESET_ENABLE 1'b0
`endif

`ifdef YUTORINA_POSITIVE_RESET
`define YUTORINA_RESET_DISABLE 1'b0
`else
`define YUTORINA_RESET_DISABLE 1'b1
`endif

`ifdef YUTORINA_POSITIVE_MEMORY
`define YUTORINA_MEM_ENABLE 1'b1
`else
`define YUTORINA_MEM_ENABLE 1'b0
`endif

`ifdef YUTORINA_POSITIVE_MEMORY
`define YUTORINA_MEM_DISABLE 1'b0
`else
`define YUTORINA_MEM_DISABLE 1'b1
`endif

`endif
