`ifndef __YUTORINA_CPU_ISA_H__
`define __YUTORINA_CPU_ISA_H__

`define YUTORINA_REGISTER_NUM           32
`define YUTORINA_REGISTER_ADDRESS_WIDTH 5
`define YutorinaRegisterAddressBus      4:0

// 命令フォーマット
// R3形式
// 31:26：種類
// 25:21：對象レジスタ
// 20:16：左邊レジスタ
// 15:11：右邊レジスタ
// 10::0：オプションなど
// R2形式
// 31:26：種類
// 25:21：對象レジスタ
// 20:16：右邊レジスタ
// 15:0：即値など
// R1形式
// 31:26：種類
// 25:21：對象レジスタ
// 25:0：即値など
// R0形式
// 31:26：種類
// 25:0：即値など

// 種類
// 算術命令
// 31:26=000000
// 25:21=對象レジスタ、20:16=左邊レジスタ、15:11=右邊レジスタ
// 10:0=オプション
`define YUTORINA_OPCODE_ARITHMETIC 6'b000000

`define YUTORINA_FUNC_ADD                    10'b0000000000
`define YUTORINA_FUNC_SUB                    10'b0000000001
`define YUTORINA_FUNC_AND                    10'b0000000010
`define YUTORINA_FUNC_OR                     10'b0000000011
`define YUTORINA_FUNC_XOR                    10'b0000000100
`define YUTORINA_FUNC_LOGICAL_SHIFT_LEFT     10'b0000000101
`define YUTORINA_FUNC_LOGICAL_SHIFT_RIGHT    10'b0000000110
`define YUTORINA_FUNC_ARITHMETIC_SHIFT_LEFT  10'b0000001101
`define YUTORINA_FUNC_ARITHMETIC_SHIFT_RIGHT 10'b0000001110

// ロード命令
`define YUTORINA_OPCODE_LOAD_WORD
`define YUTORINA_OPCODE_LOAD_HALF_WORD
`define YUTORINA_OPCODE_LOAD_BYTE

// ストア命令
`define YUTORINA_OPCODE_STORE_WORD
`define YUTORINA_OPCODE_STORE_HALF_WORD
`define YUTORINA_OPCODE_STORE_BYTE

// 算術即値命令
`define YUTORINA_OPCODE_ADD_IMMEDIATE
`define YUTORINA_OPCODE_AND_IMMEDIATE
`define YUTORINA_OPCODE_OR_IMMEDIATE
`define YUTORINA_OPCODE_XOR_IMMEDIATE
`define YUTORINA_OPCODE_LOGICAL_SHIFT_LEFT_IMMEDIATE
`define YUTORINA_OPCODE_LOGICAL_SHIFT_RIGHT_IMMEDIATE
`define YUTORINA_FUNC_ARITHMETIC_SHIFT_LEFT_IMMEDIATE
`define YUTORINA_FUNC_ARITHMETIC_SHIFT_RIGHT_IMMEDIATE

// 分岐命令
`define YUTORINA_OPCODE_BRANCH

`define YUTORINA_FUNC_EQUAL
`define YUTORINA_FUNC_NOT_EQUAL
`define YUTORINA_FUNC_GREATER_EQUAL
`define YUTORINA_FUNC_GREATER_THAN
`define YUTORINA_FUNC_LESS_EQUAL
`define YUTORINA_FUNC_LESS_THAN

`define YUTORINA_OPCODE_JUMP
`define YUTORINA_OPCODE_CALL

// 特殊命令
`define YUTORINA_OPCODE_TRAP

// 特權命令
`define YUTORINA_OPCODE_READ_CONTROL_REGISTER
`define YUTPRINA_OPCODE_WRITE_CONTROL_REGISTER
`define YUTORINA_OPCODE_EXCEPTION_RETURN

`endif
